before_script:
  - apt-get update -qy
  - apt-get install -y python3 python3-setuptools python3-certifi python3-yaml python3-numpy python3-serial python3-nose python3-coverage

test_library:
  stage: test
  script:
    - python3 setup.py nosetests --with-coverage --cover-package=inphase

documentation:
  stage: deploy
  script:
    - apt-get install -y python3-pip
    - pip3 install sphinx
    - python3 setup.py install
    - cd doc
    - make html
  artifacts:
    paths:
      - doc/build
