before_script:
  - apt-get update -qy
  - apt-get install -y python3 python3-yaml

dataformat:
  stage: test
  script:
    - cd inphase
    - ./dataformat.py

binarydecoder:
  stage: test
  script:
    - cd inphase
    - ./binarydecoder.py
